"""
Plantillas de nichos por categoría, para cargarlas con un clic en la app.
Cada categoría es una lista de líneas (nicho | sinónimos).
"""

PLANTILLAS = {
    "Mascotas y veterinaria": [
        "veterinaria | clínica veterinaria | consultorio veterinario | médico veterinario",
        "hospital veterinario | urgencias veterinarias | veterinaria 24 horas | emergencias veterinarias",
        "peluquería canina | grooming | estética canina | baño para mascotas | spa canino",
        "tienda de mascotas | pet shop | petshop | almacén de mascotas",
        "agropecuaria | almacén agropecuario | agroveterinaria | veterinaria agropecuaria",
        "alimento para mascotas | concentrado para perros | comida para mascotas | distribuidora de concentrado",
        "guardería canina | hotel para mascotas | pensión canina | hospedaje para mascotas",
        "adiestramiento canino | entrenamiento de perros | escuela canina | educación canina",
        "paseador de perros | dog walker | paseo de mascotas",
        "criadero de perros | criadero de gatos | venta de cachorros | cachorros",
        "farmacia veterinaria | droguería veterinaria | insumos veterinarios",
        "laboratorio veterinario | diagnóstico veterinario | imágenes diagnósticas veterinarias",
        "fisioterapia veterinaria | rehabilitación de mascotas | terapia física animal",
        "funeraria de mascotas | cremación de mascotas | servicios funerarios para mascotas",
        "transporte de mascotas | taxi para mascotas | traslado de mascotas",
        "adopción de mascotas | refugio de animales | fundación animal | albergue de animales",
        "acuario | tienda de acuarios | acuarística | peces ornamentales",
        "tienda de aves | pajarería | venta de aves",
        "accesorios para mascotas | ropa para mascotas | juguetes para mascotas",
        "fotografía de mascotas | fotógrafo de mascotas",
    ],
    "Salud y bienestar": [
        "gimnasios | gym | crossfit | centro de acondicionamiento físico",
        "peluquerías | salón de belleza | barbería | estética",
        "spa | centro de masajes | sauna",
        "odontología | consultorio dental | clínica dental | ortodoncia",
        "médicos | consultorio médico | centro médico | IPS | EPS",
        "óptica | optometría | oftalmología",
        "veterinaria | clínica veterinaria",
        "farmacia | droguería | farmacia de turno",
        "laboratorio clínico | toma de muestras | análisis clínicos",
        "psicólogo | consultorio psicológico | psicoterapia",
        "psiquiatra | consultorio psiquiátrico | salud mental",
        "fisioterapia | terapia física | rehabilitación",
        "dermatología | consultorio dermatológico",
        "pediatría | consultorio pediátrico",
        "ginecología | consultorio ginecológico | obstetricia",
        "cardiología | consultorio cardiológico",
        "nutrición | nutricionista | dietista",
        "terapia ocupacional | terapia del lenguaje | fonoaudiología",
        "acupuntura | medicina alternativa | homeopatía",
        "centro de imágenes diagnósticas | radiología | ecografías | resonancia magnética",
        "ambulancias | servicio de ambulancia | traslado de pacientes",
        "banco de sangre | donación de sangre",
        "hogar geriátrico | ancianato | centro de cuidado de adultos mayores",
        "centro de rehabilitación | rehabilitación de adicciones | clínica de rehabilitación",
        "clínica de estética | cirugía plástica | medicina estética",
        "audífonos | centro auditivo | audiología",
        "quiropráctico | terapia quiropráctica",
    ],
    "Comida y bebida": [
        "restaurantes | comidas rápidas | asadero",
        "cafeterías | café | panadería | repostería",
        "pizzería | comida italiana",
        "bar | discoteca | cervecería | pub",
        "heladería | postres | paletería",
        "comida china | comida oriental | comida japonesa | sushi",
        "comida mexicana | taquería",
        "comida árabe | shawarma",
        "comida vegetariana | comida vegana | comida saludable",
        "carnicería | expendio de carnes",
        "pescadería | mariscos | marisquería",
        "fruver | frutería | verdulería | plaza de mercado",
        "licorera | distribuidora de licores | depósito de cerveza",
        "chocolatería | dulcería | confitería",
        "jugos naturales | fruver de jugos | batidos",
        "food truck | comida callejera | ventas ambulantes de comida",
        "catering | banquetes | eventos gastronómicos",
        "asadero de pollo | pollo asado | comidas a la brasa",
        "panadería y pastelería | torta y ponqués | repostería fina",
        "cava de vinos | tienda de vinos | enoteca",
    ],
    "Comercio y retail": [
        "ferreterías | ferretería",
        "supermercados | minimercado | tienda de barrio",
        "ropa | boutique | almacén de ropa",
        "zapatería | calzado",
        "papelería | librería",
        "tienda de mascotas",
        "floristería",
        "joyería | relojería",
        "mueblería | muebles | decoración del hogar",
        "electrodomésticos | tecnología",
        "tienda de deportes | artículos deportivos",
        "tienda de bebés | artículos para bebés",
        "ropa deportiva | sportwear",
        "ropa infantil | almacén infantil",
        "lencería | ropa interior",
        "sex shop | tienda erótica",
        "tienda naturista | productos naturales | herbolaria",
        "miscelánea | variedades | todo a mil",
        "tienda de disfraces | piñatería | artículos para fiestas",
        "tienda de instrumentos musicales | almacén de música",
        "tienda de bicicletas | almacén de bicicletas",
        "distribuidora mayorista | mayorista | distribución al por mayor",
        "compraventa | casa de empeño | prendería",
        "tienda de colchones | almacén de colchones",
        "tienda de telas | mercería | almacén de telas",
    ],
    "Automotriz": [
        "talleres mecánicos | mecánica automotriz",
        "lavadero de carros | autolavado",
        "llantas | montallantas",
        "repuestos | autopartes",
        "motos | taller de motos | repuestos de motos",
        "concesionario de autos | venta de vehículos",
        "parqueadero | parking | estacionamiento",
        "polarizado de vidrios | accesorios para carros",
        "aire acondicionado automotriz | electricidad automotriz",
        "grúa | remolque de vehículos | servicio de grúa",
        "alquiler de autos | renta de carros | rent a car",
        "lavado de motos | taller de motos",
        "pintura automotriz | latonería y pintura",
        "chatarrería de autos | desguace | autopartes usadas",
        "estación de servicio | gasolinera | bomba de gasolina",
    ],
    "Servicios profesionales": [
        "abogados | oficina jurídica | firma de abogados",
        "contadores | contaduría | asesoría contable",
        "inmobiliaria | finca raíz | agencia inmobiliaria",
        "agencia de viajes | operador turístico",
        "imprenta | publicidad | diseño gráfico",
        "notaría",
        "seguros | aseguradora | corredor de seguros",
        "arquitectos | estudio de arquitectura",
        "ingenieros | consultoría de ingeniería",
        "agencia de marketing digital | agencia de publicidad digital | community manager",
        "traductores | servicios de traducción | intérpretes",
        "recursos humanos | agencia de empleo | bolsa de empleo",
        "consultoría empresarial | asesoría empresarial",
        "auditoría | revisoría fiscal",
        "agencia aduanera | comercio exterior",
        "mensajería | paquetería | courier",
        "call center | centro de contacto | BPO",
        "estudio contable y tributario | declaración de renta",
    ],
    "Educación": [
        "colegios | institución educativa",
        "jardín infantil | guardería | preescolar",
        "academia | instituto | centro de idiomas",
        "universidad",
        "autoescuela | escuela de conducción",
        "capacitación técnica | educación para el trabajo | SENA",
        "escuela de música | academia de música",
        "escuela de arte | academia de arte",
        "escuela de danza | academia de baile",
        "tutoría escolar | refuerzo académico | clases particulares",
        "biblioteca | centro de estudio",
        "academia de sistemas | curso de computación",
    ],
    "Hogar y construcción": [
        "constructora | construcción",
        "carpintería | ebanistería",
        "cerrajería",
        "vidriería",
        "plomería | fontanería",
        "electricista",
        "pintores | pintura de interiores | pintura de fachadas",
        "techos y cubiertas | impermeabilización",
        "jardinería | paisajismo | mantenimiento de jardines",
        "piscinas | mantenimiento de piscinas",
        "aire acondicionado | refrigeración | climatización",
        "seguridad electrónica | alarmas | cámaras de vigilancia",
        "pisos y cerámica | enchapes",
        "remodelaciones | acabados de construcción",
        "mudanzas | trasteos | transporte de muebles",
        "control de plagas | fumigación",
        "servicios de aseo | limpieza | empresa de servicios generales",
        "materiales de construcción | depósito de materiales",
        "arriendo de maquinaria | alquiler de andamios",
        "diseño de interiores | decoración de interiores",
    ],
    "Belleza y cuidado personal": [
        "uñas | manicure | spa de uñas",
        "tatuajes | estudio de tatuajes | piercing",
        "yoga | pilates",
        "depilación | centro de depilación láser",
        "maquillaje | make up artist | maquilladora profesional",
        "extensiones de pestañas | lash studio",
        "barbería | afeitada clásica",
    ],
    "Hospedaje y eventos": [
        "hoteles | hostal | hospedaje",
        "salón de eventos | eventos",
        "fotografía | fotógrafo",
        "finca | alquiler de fincas | finca para eventos",
        "decoración de eventos | ambientación de eventos",
        "alquiler de carpas | alquiler de sillas y mesas | menaje para eventos",
        "wedding planner | organización de bodas",
        "DJ | sonido para eventos | iluminación para eventos",
        "cabañas | glamping | camping",
        "video para eventos | filmación de eventos",
    ],
    "Tecnología y electrónica": [
        "reparación de celulares | técnico de celulares",
        "servicio técnico de computadores | reparación de computadores",
        "tienda de tecnología | almacén de tecnología",
        "cámaras de seguridad | instalación de CCTV",
        "telecomunicaciones | proveedor de internet",
        "desarrollo de software | agencia de desarrollo web",
        "cyber café | café internet",
        "venta de celulares | distribuidor de celulares",
        "impresión 3D | servicio de impresión 3D",
        "reparación de electrodomésticos | técnico de electrodomésticos",
    ],
    "Agropecuario e industrial": [
        "agroindustria | insumos agrícolas",
        "maquinaria industrial | venta de maquinaria",
        "metalmecánica | taller de metalmecánica",
        "soldadura | taller de soldadura",
        "bodega | almacenamiento | centro de logística",
        "distribuidora industrial | insumos industriales",
        "reciclaje | chatarrería | compra de material reciclable",
        "avicultura | granja avícola | venta de pollos",
        "cultivo agrícola | finca agrícola | agroexportadora",
    ],
    "Financiero y seguros": [
        "bancos | sucursal bancaria | corresponsal bancario",
        "cooperativas financieras | fondo de empleados",
        "casa de cambio | cambio de divisas",
        "compraventa | casa de empeño",
        "seguros | aseguradora | corredor de seguros",
        "asesoría financiera | asesor de inversiones",
        "exchange de criptomonedas | compra venta de criptomonedas",
        "libranzas | créditos y préstamos | prestamista",
    ],
    "Religioso y espiritual": [
        "iglesia | templo | parroquia",
        "funeraria | servicios funerarios | sala de velación",
        "cementerio | parque cementerio | cremación",
        "tarotista | vidente | esoterismo",
        "librería religiosa | artículos religiosos",
    ],
    "Transporte y logística": [
        "transporte de carga | empresa de transporte",
        "mensajería | courier",
        "taxi | servicio de taxi",
        "agencia de mudanzas | trasteos",
        "alquiler de vehículos | rent a car",
        "parqueadero | estacionamiento",
        "transporte escolar | ruta escolar",
        "transporte intermunicipal | terminal de transporte",
        "operador logístico | almacenamiento y distribución",
    ],
    "Entretenimiento y recreación": [
        "cine | teatro",
        "parque de diversiones | parque temático",
        "billar | salón de billar",
        "bolera | boliche",
        "arcade | sala de videojuegos",
        "karaoke | bar de karaoke",
        "casino | sala de juegos",
        "parque acuático | piscina recreativa",
        "escape room",
        "cancha sintética | cancha de fútbol | complejo deportivo",
        "club deportivo | academia de fútbol | escuela deportiva",
    ],
    "Gobierno y trámites": [
        "notaría",
        "curaduría urbana | licencias de construcción",
        "cámara de comercio",
        "oficina de tránsito | trámites vehiculares",
        "registraduría | trámites de identificación",
    ],
}


def categorias():
    return list(PLANTILLAS.keys())


def nichos_de(categoria):
    return PLANTILLAS.get(categoria, [])
